### PR TITLE
fix/202: make "You're connected to Square" page entire UI to be visible

### LINKED ISSUE #202: Reduce the vertical spacing on "Enable Payment Methods" step
### Describe the bug

As per the [internal discussion](https://fueled10up.slack.com/archives/C01UCQGPBDJ/p1724074162197069?thread_ts=1723037634.886629&cid=C01UCQGPBDJ), reduce the vertical space for the portions in the "Enable Payment Methods" section so that the Next button raises up "above the fold" and becomes visible without having to scroll.

### To reproduce

Try to see the wizard in the lower resolution (1280x720) and see the Next button is not visible above-the-fold on the "Enable Payment Methods" wizard step.

### Expected behavior

In at least 1280x720 resolution, the Next button should be visible in the above-the-fold, scrolling shouldn't be required to see it.

image

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

This PR uses combination of max/min - width/height media queries to ensure the "Next" button is always visible on the screen for desktop resolution as low as `1280 x 720`.

Closes #202
Closes https://linear.app/a8c/issue/SQUARE-131/reduce-the-vertical-spacing-on-enable-payment-methods-step 

### Steps to test the changes in this Pull Request:

- Test for minimum desktop resolution of `1280 x 720`
- Test for mobile resolution.

### Changelog entry

> Fix - Vertical spacing on "Enable Payment Methods" step.

### CODE REVIEW

File: src/new-user-experience/components/onboarding-header/index.js [hunk 1]
```diff
@@ -20,38 +20,36 @@ export const OnboardingHeader = () => {
...
+			<div className="flexItem closeWizard">
+				<Button
+					onClick={ () => {
+						queueRecordEvent(
+							ONBOARDING_TRACK_EVENTS.EXIT_CLICKED,
+							{
+								exited_on_step: stepData.step,
+							}
+						);
+						window.location.href =
```
Comment (dkotter) [inline src/new-user-experience/components/onboarding-header/index.js]: Looks like an eslint issue that needs cleaned up here

**Review by dkotter — CHANGES_REQUESTED** [review]

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
QA Update: ❌
---

@Sidsector9  Thanks for the PR

I cross-checked with the `fix/202` branch, and it seems like the designs for the following screens are not displaying properly:

- Select your business location
- Configure sync setting
- Manage payment method

Could you please check from your end as well?
 

https://github.com/user-attachments/assets/f9a6e332-9f57-4d80-a3eb-9eaef0f18c05

**Comment by qasumitbagthariya** [comment]
QA Update: ❌
---

@Sidsector9 

Issue - 1

Unable to scroll down in 1024x768 resolution.

image

https://github.com/user-attachments/assets/0d96116f-3f26-4416-97b3-65627de38948

----
Issue - 2

In this, fix branch I notice Some screen settings are flickering while selecting.

https://github.com/user-attachments/assets/26928a70-1745-4517-8dad-429fe17eae57

**Comment by Sidsector9** [comment]
@qasumitbagthariya as discussed on Slack, the minimum supported screen size is `1200 x 900px`.

**Comment by qasumitbagthariya** [comment]
QA Update: ⚠️ 
--- 

@Sidsector9 

I notice that the Next button at the bottom right corner is partially hidden and not fully visible to the user. This may affect usability, as users might struggle to scroll and proceed to the next step.

My screen resolution is 1512*982

image

---

I just want to confirm — have we made changes to the Manage Payment Methods UI? Because earlier it looked a bit different, with a smaller-sized button.

**Fix PR**
image

**Before:**
image

**Comment by jeffpaul** [comment]
@Sidsector9 @qasumitbagthariya I think I'm fine with the current state of the updated UX here... not seeing any MAJOR issues so any concerns with us moving this along for UAT?

**Comment by Sidsector9** [comment]
@jeffpaul I'm cool with the current state as well. @qasumitbagthariya what say you?

**Comment by qasumitbagthariya** [comment]
@jeffpaul yes, the current state looks good to me as well.

> @jeffpaul I'm cool with the current state as well. @qasumitbagthariya what say you?

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.8.4, npm version 10.8.2, node version 20.18.1)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.8.2
- Theme: Twenty Twenty-Five 1.2
- WooCommerce - 10.1.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>

Next Step- Ready to Merge 🚀

**Review by qasumitbagthariya — APPROVED** [review]
