### PR TITLE
fix/292: Add support for WooCommerce's new Email Improvements feature added in 9.6

### LINKED ISSUE #292: WooCommerce Square emails produce errors in WooCommerce email settings preview
### Describe the bug

WooCommerce Square emails produce errors in WooCommerce email settings preview.

### To Reproduce

1. Use **WooCommerce 9.8.0-dev** (or 9.7 Beta).
2. Enable the **Email improvements** feature flag in **WooCommerce > Settings > Advanced > Features > Experimental features**.
3. Enable `WP_DEBUG`.
4. Make sure **WooCommerce Square** is enabled.
5. Go to **WooCommerce > Settings > Emails**.
6. Scroll down to the email preview section.
7. Select an email template related to **WooCommerce Square** in the dropdown (Square sync completed, Square Gift Card sent).
8. Observe the errors. Examples:
8.1. `Function status was called incorrectly`.
8.2. Placeholders like `{product_count}`, `{sync_completed_date}`, `{sync_completed_date}` not replaced with dummy values.
8.3. Undefined stdClass properties.
8.3. Missing some content like gift card code.
9. Try changing global email template styles like colors, font, logo, header alignment, footer text and see if changes are applied to your plugin's templates. If you notice something else that is off in your plugin's email template previews, feel free to improve it as well.

### Screenshots

Image
Image

### Expected behavior

WooCommerce Square email previews work correctly.

### Desktop (please complete the following information):

* OS: Any OS
* Browser: Any browser

### Additional context

WooCommerce version: 		9.8.0-dev
WordPress version: 		6.7.2
Server info: 		PHP/8.3.14

### Tips for fixing

Each error needs to be treated separately, but here are some general useful things.

Empty values, deprecation notices and general rendering errors are usually caused by missing email-specific variables in the preview, e.g. placeholder replacement values, custom email and order details etc. These variables can't be taken from the method that sends the actual email. Dummy values for the preview need to be explicitly provided by a plugin which adds its own email templates.

There is a new [`woocommerce_email_preview_placeholders`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L352-L360) filter to add more placeholders to be replaced that some of your emails may use.

Also, filters are now available to add additional data you might need for emails to be rendered properly in previews:
[`woocommerce_email_preview_dummy_order`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L274-L282)
[`woocommerce_email_preview_dummy_product`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L296-L304)
[`woocommerce_email_preview_dummy_address`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L296-L304)

Another group of filters is for adding support for custom fields and styles your emails might use: [`woocommerce_email_preview_email_content_setting_ids`](https://github.com/woocommerce/woocommerce/blob/fd60f275f51d7ededf69b27b6a884b25251ea3c9/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L156), [`woocommerce_email_preview_email_style_setting_ids`](https://github.com/woocommerce/woocommerce/blob/fd60f275f51d7ededf69b27b6a884b25251ea3c9/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L129).

Let me know if you need any more help in fixing the issues described above.

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

This PR adds support for Email Previewer added in Woo 9.6.
I had to remove namespaces from Email Notification classes as it caused the preview to be shown at `/wp-admin/admin.php?page=wc-settings&tab=email` but the preview did not work inside each Email setting.

Closes #292 

### Steps to test the changes in this Pull Request:

1. Use **WooCommerce 9.8.0-dev** (or 9.7 Beta).
2. Enable the **Email improvements** feature flag in **WooCommerce > Settings > Advanced > Features > Experimental features**.
3. Make sure **WooCommerce Square** is enabled.
4. Go to **WooCommerce > Settings > Emails**.
5. Scroll down to the email preview section.
6. Select an email template related to **WooCommerce Square** in the dropdown

Also test with older versions of Woo.

### Changelog entry

> Add - Support for WooCommerce's new Email Improvements feature.

### CODE REVIEW

File: includes/Emails/WC_Square_Gift_Card_Sent.php [hunk 1]
```diff
@@ -0,0 +1,306 @@
...
+			}
+
+			$result['sender_name']       = $item->get_meta( 'square-gift-card-sender-name' );
+			$result['sender_message']    = $item->get_meta( 'square-gift-card-sent-to-message' );
+			$result['recipient_name']    = $item->get_meta( 'square-gift-card-sent-to-first-name' );
+			$result['gift_card_number']  = wc_square()->get_gateway( $order->get_payment_method() )->get_order_meta( $order, 'gift_card_number' );
+			$result['gift_card_balance'] = wc_square()->get_gateway( $order->get_payment_method() )->get_order_meta( $order, 'gift_card_balance' );
+		}
+
+		return isset( $result[ $key ] ) ? $result[ $key ] : '';
```
Comment (dkotter) [inline includes/Emails/WC_Square_Gift_Card_Sent.php]:
```suggestion
		return $result[ $key ] ?? '';
```

File: includes/Emails/WC_Square_Gift_Card_Sent.php [hunk 2]
```diff
@@ -0,0 +1,306 @@
...
+	}
+
+	/**
+	 * Says if a Gift card was purchased in the order.
```
Comment (dkotter) [inline includes/Emails/WC_Square_Gift_Card_Sent.php]:
```suggestion
	 * Check if order contains a gift card.
```

**Review by dkotter — COMMENTED** [review]
Overall looks good. A few minor things and also seeing a couple PHPCS warnings that need cleaned up

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update  ✅
-------------

I have verified this PR in the `fix/292` branch which has been fixed and is functioning as intended.

I tested the following on this branch:
- Test Email functionality with Woo Beta 9.8.0-beta.1 and 9.7.1

image

image

image


**Testing Environment** 

<Details>

- WordPress: 6.7.2
- Theme: Storefront 4.6.1
- Theme: Twenty Twenty-Four 1.3
- WooCommerce - 9.7.1 / Beta 9.8.0-beta.1 
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: fix/292

</Details>


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Review by brucealdridge — APPROVED** [review]
✅ Tested against WC 9.8 beta

Read through code changes.
PR Testing instructions were missing crucial details, copied in repoduction instructions from Issue.

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.8.4, npm version 10.8.2, node version 20.18.1)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.7.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.3
- WooCommerce - 9.5.1 / 9.8.0-rc.1 
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀
