### PR TITLE
Fix/66: Fix the repetitive creation of 'wc_square_init_payment_token_migration' actions in the payment token migration process.

### LINKED ISSUE #66: ‘wc_square_init_payment_token_migration’ Action Scheduler Event Huge Issue
The plugin is breaking my site due to the ‘wc_square_init_payment_token_migration’ action scheduler event. It’s running in a loop and adding hundreds of thousands of events to the queue, all with the same args.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
PR fixes the repetitive creation of 'wc_square_init_payment_token_migration' scheduled actions, which is used for migrating payment tokens from user_meta to WC_Payment_Token_CC.

**Root cause:**
Currently, the payment token migration function processes users in batches (5 users per batch) and schedules a new action to process the next batch of users until no pending users remain. This migration action hook was added in the payment tokens handler class. In the 4.5.0 release, we added a new payment gateway. With the addition of the new gateway, the payment tokens handler class gets registered twice, and the migration function is called twice for a single scheduled action. This results in registering too many actions if the site has a good number of users.

**Note:** This issue only affects the sites that upgrade the plugin from version <3.7.1 to 4.5.0 and the fresh installations.

The PR resolves the issue by relocating the migration function to the Plugin class. In addition to moving the action hook and migration function, the PR also cleans up the existing scheduled actions for migrations to tidy up the database and the processing. It updates the action name by appending `_v2` to prevent any conflicts. Also, updates get users query to get users with tokens only.

Closes #66 

### Steps to test the changes in this Pull Request:
1. Checkout to the `trunk` branch.
1. Make sure the site has enough number of users (30-40 will be fine) to reproduce the issue.
1. Go to the options table and remove option `wc_square_payment_token_migration_complete` from db. It will help to initiate the migration process. OR create a completely new site setup and install the Square plugin.
1. Go to `Tools` > `Scheduled Actions`, Refresh it 2-3 times
1. Notice there is multiple actions are created with the `wc_square_init_payment_token_migration` action hook with the same arguments `'page' => x`
1. Checkout to the `fix/66` branch.
1. Go to `Tools` > `Scheduled Actions`
1. Verify that created actions are cleared and payment token is migrated successfully for all users.
1. You can remove the `wc_square_payment_token_migration_complete` option again to initiate the migration process for the beginning and verify there are no multiple actions created with the fix branch.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

 I have checked this issue in the fix/66 branch and the related issue is resolved and working as expected.


**Testing Environment** 

<Details>

- WordPress: 6.4.3
- Theme: Storefront 4.5.4
- WooCommerce - 8.6.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


https://github.com/woocommerce/woocommerce-square/assets/67687255/60312530-c169-4fa3-b32d-5847ffbc213e



Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR

**Review by qasumitbagthariya — APPROVED** [review]

File: includes/Gateway/Cash_App_Pay_Gateway.php [hunk 1]
```diff
@@ -415,6 +415,15 @@ protected function get_method_form_fields() {
 		return array();
 	}
 
+	/**
+	 * Initialize payment tokens handler.
+	 *
+	 * @since x.x.x
+	 */
+	protected function init_payment_tokens_handler() {
```
Comment (wjrosa) [inline includes/Gateway/Cash_App_Pay_Gateway.php:423]: Do we really need this empty method? 🤔 Edit: I see, this is to avoid the inherited code to run for this class 👍 .

**Review by wjrosa — APPROVED** [review]
LGTM!

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

Next Step- Ready to Merge 🚀


**Testing Environment** 

<Details>

- WordPress: 6.4.3
- Theme: Storefront 4.5.4
- WooCommerce - 8.6.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


Status update:
cc @vikrampm1
