### PR TITLE
[NUX]: Onboarding + settings pages

### LINKED ISSUE #58: Duplicate Configure link, under the plugin's name, in the page at WooCommerce > Plugins
### Describe the bug

Both `Configure` links, link to the Square tab, under WooCommerce > Settings.
None to the screen at WooCommerce > Settings > Payments > Square.

### To reproduce

1. Have version 4.5.0 of the plugin installed

**Screenshots**

Screenshot 2024-02-02 at 10 46 19

### Expected behavior

To have two links, appropriately named, linking to each settings screen.

**Environment (please complete the following information):**
 - WordPress Version 6.4.3
 - WooCommerce Version 8.5.2
 - WooCommerce Square Plugin Version 4.5.0
 - Browser [e.g. chrome, safari] and Version → Chrome Version 121.0.6167.139 (Official Build) (arm64)
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
`
### WordPress Environment ###

WordPress address (URL): https://example.com
Site address (URL): https://example.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 63.45MB
Database Data Size: 37.37MB
Database Index Size: 26.08MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_actions: Data: 4.47MB + Index: 3.17MB + Engine InnoDB
vp_backup_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_logs: Data: 2.48MB + Index: 3.02MB + Engine InnoDB
vp_backup_wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
vp_backup_wp_gla_merchant_issues: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_options: Data: 1.45MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 0.39MB + Index: 0.41MB + Engine InnoDB
vp_backup_wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.03MB + Index: 1.86MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 2.06MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.25MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.45MB + Index: 0.47MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 0.13MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.03MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 6.02MB + Index: 4.00MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 2.02MB + Index: 2.48MB + Engine InnoDB
__wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
__wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
__wp_gla_merchant_issues: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
__wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 1.11MB + Index: 0.08MB + Engine InnoDB
__wp_postmeta: Data: 0.38MB + Index: 0.34MB + Engine InnoDB
__wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
__wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
__wp_wc_orders_meta: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 17
aw_workflow: 1
bookable_person: 2
custom_css: 1
global_product_addon: 1
jp_pay_product: 3
nav_menu_item: 7
page: 26
post: 46
product: 40
product_variation: 111
revision: 184
shop_coupon: 3
shop_order: 46
shop_order_refund: 2
shop_subscription: 4
wc_booking: 1
wp_global_styles: 2
wp_navigation: 1
wp_template: 3
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Facebook for WooCommerce: by Facebook – 3.1.9
Jetpack Protect: by Automattic - Jetpack Security team – 2.0.0
Jetpack: by Automattic – 13.1-a.9
WooCommerce Square: by WooCommerce – 4.5.0
WooCommerce: by Automattic – 8.5.2

### Inactive Plugins (33) ###

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-03 07:33:28 +01:00
Options: ✔
Notes: 44
Onboarding: skipped

### Action Scheduler ###

Complete: 172
Oldest: 2024-01-02 13:53:17 +0100
Newest: 2024-02-02 10:46:44 +0100

Failed: 2,298
Oldest: 2023-06-08 12:06:57 +0200
Newest: 2024-01-19 10:49:18 +0100

Pending: 2
Oldest: 2024-02-02 14:45:42 +0100
Newest: 2024-02-18 10:49:18 +0100


### Status report information ###

Generated at: 2024-02-02 10:55:26 +01:00
`
  ```
</details>

### LINKED ISSUE #89: NUX Updates to Merchant Onboarding
To review and improve the merchant onboarding experiences and make WooCommerce + Square integration and sync settings more intuitive. To improve the ability for the Square extension to be quickly set up when used only for payment processing and  minimise the number of steps and checkboxes that the merchants have to perform the WooCommerce + Square integration and sync, making it seamless and more intuitive. This enhancement includes the following tasks:

- [ ] Map the UX flows to set up Square more quickly when used only for payment processing
- [ ] Map the UX flows to minimize the number of steps and checkboxes that the merchants have to perform the WooCommerce + Square integration and sync
- [ ] Map the additional UX flows, as necessary, for any additional merchant onboarding recommendations
- [ ] Add e2e tests where necessary

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes #89, Closes #58.

This PR improves the merchant onboarding experiences and makes WooCommerce + Square integration and sync settings more intuitive.

image

image

image

image

image

image

image

### Steps to test the changes in this Pull Request:

The brand new onboarding wizard flow and settings pages should work as per [PT: NUX Improvements for Square](https://10upwoo.wordpress.com/2024/01/30/pt-nux-improvements-for-square/).

Notes:

- The "business location" step is displayed right after the successful connection and the "payment methods" page is displayed later.
- On the settings page, the business location field is moved after the connection field as it makes more sense.

### Changelog entry

> Add - New Merchant Onboarding experience with the new wizard flow & settings pages.

### CODE REVIEW

File: assets/new-user-experience/components/onboarding-header/index.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+ * Internal dependencies
+ */
+import './index.scss';
+import { Back, Square, Close } from '../../icons';
+import { useSteps } from './../../onboarding/hooks';
+
+export const OnboardingHeader = () => {
+    const {
+		setStep,
+        getBackStep,
```
Comment (dkotter) [inline assets/new-user-experience/components/onboarding-header/index.js]: Looks like some weird spacing here

File: assets/new-user-experience/icons/back.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+export const Back = () => {
+	return (
```
Comment (dkotter) [inline assets/new-user-experience/icons/back.js:2]: Looks like an extra tab here or a mix of tabs and spaces in this file

File: assets/new-user-experience/icons/close.js [hunk 3]
```diff
@@ -0,0 +1,7 @@
+export const Close = () => {
+	return (
```
Comment (dkotter) [inline assets/new-user-experience/icons/close.js:2]: Looks like an extra tab here or a mix of tabs and spaces in this file

File: assets/new-user-experience/icons/manage.js [hunk 4]
```diff
@@ -0,0 +1,8 @@
+export const Manage = () => {
+	return (
```
Comment (dkotter) [inline assets/new-user-experience/icons/manage.js:2]: Looks like an extra tab here or a mix of tabs and spaces in this file

File: assets/new-user-experience/icons/square.js [hunk 5]
```diff
@@ -0,0 +1,14 @@
+export const Square = () => {
+	return (
```
Comment (dkotter) [inline assets/new-user-experience/icons/square.js:2]: Looks like an extra tab here or a mix of tabs and spaces in this file

File: assets/new-user-experience/icons/sync.js [hunk 6]
```diff
@@ -0,0 +1,8 @@
+export const Sync = () => {
+	return (
```
Comment (dkotter) [inline assets/new-user-experience/icons/sync.js:2]: Looks like an extra tab here or a mix of tabs and spaces in this file

File: assets/new-user-experience/modules/advanced-settings/index.js [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+			step,
+		}
+	} = useSteps();
+
+	const {
+		enable_customer_decline_messages,
+		debug_logging_enabled = 'no',
+	} = settings;
+
+	if ( ! ( squareSettingsLoaded ) ) {
```
Comment (dkotter) [inline assets/new-user-experience/modules/advanced-settings/index.js]: Do we need the extra parentheses here?
```suggestion
	if ( ! squareSettingsLoaded ) {
```

File: assets/new-user-experience/modules/advanced-settings/index.js [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+
+				<div className='woo-square-wizard__fields'>
+					<InputWrapper
+						label={ __( 'Detailed Decline Messages', 'woocommerce-square' ) }
+					>
+						<SquareCheckboxControl
+							checked={ 'yes' === enable_customer_decline_messages }
+							onChange={ ( enabled ) => setSquareSettingData( { enable_customer_decline_messages: enabled ? 'yes' : 'no' } ) }
+							label={
+								__( 'Check to enable detailed decline messages to the customer during checkout when possible, rather than a generic decline message.', 'woocommerce-square' )
```
Comment (dkotter) [inline assets/new-user-experience/modules/advanced-settings/index.js]: Just my opinion but seems pretty obvious that they need to check this option to turn it on so not sure we need that in a label/description. I'd do something like:
```suggestion
								__( 'Show detailed decline messages to the customer during checkout rather than a generic decline message.', 'woocommerce-square' )
```

File: assets/new-user-experience/modules/advanced-settings/index.js [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+							}
+						/>
+					</InputWrapper>
+
+					<DebugMode />
+
+					<InputWrapper
+						label={ __( 'Enable Logging', 'woocommerce-square' ) }
+						variant="boxed"
+						description={ __( 'After enabling you’ll see a new Sandbox settings section with two fields; Sandbox Application ID & Sandbox Access Token.', 'woocommerce-square' )}
```
Comment (dkotter) [inline assets/new-user-experience/modules/advanced-settings/index.js]:
```suggestion
						description={ __( 'After enabling you’ll see a new Sandbox settings section with two fields: Sandbox Application ID & Sandbox Access Token.', 'woocommerce-square' )}
```

File: assets/new-user-experience/modules/configure-sync/index.js [hunk 10]
```diff
@@ -0,0 +1,304 @@
...
+	const {
+		system_of_record = 'disabled',
+		enable_inventory_sync = 'no',
+		override_product_images = 'no',
+		hide_missing_products = 'no',
+		sync_interval = '0.25',
+		is_connected = false,
+	} = settings;
+
+	const sync_interval_options = [
```
Comment (dkotter) [inline assets/new-user-experience/modules/configure-sync/index.js:47]: I've not gotten further yet so maybe I'll find the answer to this later but if I recall correctly, we have a PHP filter right now allowing these options to be changed. Is that something that can still be done in this new experience?

File: assets/new-user-experience/modules/sandbox-settings/index.js [hunk 11]
```diff
@@ -0,0 +1,87 @@
...
+			<Section>
+				<SectionTitle title={ __( 'Configure Sandbox Settings', 'woocommerce-square' ) } />
+				<SectionDescription>
+					{ __( 'Activate Sandbox Mode to safely simulate transactions and sync operations, ensuring your WooCommerce/Square integration functions seamlessly. Experiment with payment methods and product data syncing in a risk-free environment before going live with your store.', 'woocommerce-square' ) }
+				</SectionDescription>
+
+				<div className='woo-square-wizard__fields'>
+					<InputWrapper
+						label={ __( 'Enable Sandbox Mode', 'woocommerce-square' ) }
+						description={ __( "After enabling you'll see a new Sandbox settings section with two fields; Sandbox Application ID & Sandbox Access Token.", 'woocommerce-square' ) }
```
Comment (dkotter) [inline assets/new-user-experience/modules/sandbox-settings/index.js]:
```suggestion
						description={ __( "After enabling you'll see a new Sandbox settings section with two fields: Sandbox Application ID & Sandbox Access Token.", 'woocommerce-square' ) }
```

File: assets/new-user-experience/modules/sandbox-settings/index.js [hunk 12]
```diff
@@ -0,0 +1,87 @@
...
+							checked={ 'yes' === enable_sandbox }
+							onChange={ ( enable_sandbox ) => setSquareSettingData( { enable_sandbox: enable_sandbox ? 'yes' : 'no' } ) }
+						/>
+					</InputWrapper>
+
+					{ 'yes' === enable_sandbox && (
+						<>
+							<InputWrapper
+								label={ __( 'Sandbox Application ID', 'woocommerce-square' ) }
+								description={ __( 'Application ID for the Sandbox Application, see the details in the My Applications section.', 'woocommerce-square' ) }
```
Comment (dkotter) [inline assets/new-user-experience/modules/sandbox-settings/index.js]: Could we link to the correct spot, the `My Applications` page?

File: assets/new-user-experience/modules/sandbox-settings/index.js [hunk 13]
```diff
@@ -0,0 +1,87 @@
...
+							>
+								<TextControl
+									value={ sandbox_application_id }
+									onChange={ ( sandbox_application_id ) => setSquareSettingData( { sandbox_application_id } ) }
+								/>
+							</InputWrapper>
+
+							<InputWrapper
+								label={ __( 'Sandbox Access Token', 'woocommerce-square' ) }
+								description={ __( 'Access Token for the Sandbox Test Account, see the details in the Sandbox Test Account section. Make sure you use the correct Sandbox Access Token for your application. For a given Sandbox Test Account, each Authorized Application is assigned a different Access Token.', 'woocommerce-square' ) }
```
Comment (dkotter) [inline assets/new-user-experience/modules/sandbox-settings/index.js]: Same here, would be great to link to the right spot if we can

File: assets/new-user-experience/onboarding/data/reducers.js [hunk 14]
```diff
@@ -0,0 +1,201 @@
+export const CREDIT_CARD_DEFAULT_STATE = {
+	enabled: 'yes',
+	title: 'Credit Card',
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/data/reducers.js]: There's a decent amount of text in this file that isn't being translated. I've not parsed everything yet so maybe that doesn't matter but flagging that as something to consider if needed.

File: assets/new-user-experience/onboarding/hooks/index.js [hunk 15]
```diff
@@ -0,0 +1,210 @@
...
+
+	const getStep = ( key ) => useSelect( ( select ) => select( store ).getStep( key ) );
+	const getBackStep = ( key ) => useSelect( ( select ) => select( store ).getBackStep( key ) );
+
+	const setStep = ( data ) => dispatch( store ).setStep( data );
+	const setBackStep = ( data ) => dispatch( store ).setBackStep( data );
+
+	const stepData = {
+		// step: localStorage.getItem('step') || getStep(),
+		// backStep: localStorage.getItem('backStep') || getBackStep(),
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/hooks/index.js]: Assuming we can remove this

File: assets/new-user-experience/onboarding/onboarding-app.js [hunk 16]
```diff
@@ -0,0 +1,215 @@
...
+
+	const useSquareSettingsData = useSquareSettings( true );
+
+	const {
+		settings,
+		squareSettingsLoaded
+	} = useSquareSettingsData;
+
+	// Set info in local storage.
+	useEffect(() => {
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/onboarding-app.js:57]: Seeing a mix of styling in this file, some places don't have spaces (like here) but others do. We should standardize that to match what we're doing elsewhere (looks like adding spaces is the desired outcome)

File: assets/new-user-experience/onboarding/steps/business-location/index.js [hunk 17]
```diff
@@ -0,0 +1,108 @@
...
+	const locationCount = locations.length;
+	const buttonText = 1 === locationCount ? __( 'Confirm', 'woocommerce-square' ) : __( 'Next', 'woocommerce-square' );
+
+	const noLocation = (
+		<>
+			<Section>
+				<SectionTitle title={ __( 'Your Square account is missing a Business Location', 'woocommerce-square' ) } />
+				<SectionDescription>
+					<p>
+						{ __( 'Please go here or use the button below to create a Business Location and then return to WooCommerce to complete setup.', 'woocommerce-square' ) }
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/steps/business-location/index.js]: Are the words `go here` supposed to be linked somewhere?

File: assets/new-user-experience/onboarding/steps/business-location/index.js [hunk 18]
```diff
@@ -0,0 +1,108 @@
...
+					{ __( "Please select the location you wish to link with this WooCommerce store", 'woocommerce-square' ) }
+				</p>
+			</SectionDescription>
+		</>
+	);
+
+	return (
+		<div>
+			<Section>
+				{(locationCount === 0 && noLocation) ||
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/steps/business-location/index.js:168]: Same question here in regards to spacing. I see a few places here and later in the file that don't have spaces while the rest of the code does

File: assets/new-user-experience/onboarding/steps/digital-wallets/index.js [hunk 19]
```diff
@@ -0,0 +1,156 @@
...
+	if ( ! paymentGatewaySettingsLoaded ) {
+		return null;
+	}
+
+	return (
+		<>
+			<Section>
+				<SectionTitle title={ __( 'Manage Digital Wallet Settings', 'woocommerce-square' ) } />
+				<SectionDescription>
+					{ __( 'Accept payments with Apple Pay and Google Pay on your store, available in select countries. Enabling digital wallets adds payment buttons to Product, Cart, and Checkout pages.', 'woocommerce-square' ) }
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/steps/digital-wallets/index.js]:
```suggestion
					{ __( 'Accept payments with Apple Pay and Google Pay on your store, available in select countries. Enabling digital wallets adds payment buttons to Product, Cart and Checkout pages.', 'woocommerce-square' ) }
```

File: assets/new-user-experience/onboarding/steps/payment-complete/index.js [hunk 20]
```diff
@@ -0,0 +1,184 @@
...
+			<div className="woo-square-onbarding__payment-settings">
+				<div className="woo-square-onbarding__payment-settings--left">
+					<div className="woo-square-onbarding__payment-settings__intro">
+						<div className="woo-square-onbarding__payment-settings__intro--title">
+							{ __( "Congratulations,", 'woocommerce-square' ) }
+							<br />
+							{ __( "Your Payment Setup is Complete!", 'woocommerce-square' ) }
+						</div>
+						<SectionDescription>
+							{ __( "Your online store is now equipped to accept payments, making you ready to welcome customers and start generating sales.", 'woocommerce-square' ) }
```
Comment (dkotter) [inline assets/new-user-experience/onboarding/steps/payment-complete/index.js]: Seems like all these text strings can be wrapped in single quotes instead of double

File: assets/new-user-experience/styles/fonts/sf-pro/SFPRODISPLAYBLACKITALIC.OTF
Comment (dkotter) [inline assets/new-user-experience/styles/fonts/sf-pro/SFPRODISPLAYBLACKITALIC.OTF:1]: Curious if all of these fonts are actually used? Would prefer not to bundle any that aren't but maybe all of them are needed

File: assets/new-user-experience/styles/index.scss [hunk 21]
```diff
@@ -0,0 +1,205 @@
+// import fonts SFPRODISPLAYREGULAR.OTF from /Users/faisalalvi/LocalSites/wpne/app/public/wp-content/plugins/woocommerce-square/assets/new-user-experience/fonts/sf-pro/SFPRODISPLAYREGULAR.OTF
```
Comment (dkotter) [inline assets/new-user-experience/styles/index.scss]: Assuming we can remove this

File: assets/onboarding/components/index.js
Comment (dkotter) [inline assets/onboarding/components/index.js:1]: Do we need this file? Says it's empty

File: assets/onboarding/elements/index.js
Comment (dkotter) [inline assets/onboarding/elements/index.js:1]: Do we need this file? Says it's empty

File: assets/onboarding/hooks/index.js
Comment (dkotter) [inline assets/onboarding/hooks/index.js:1]: Do we need this file? Says it's empty

File: assets/onboarding/steps/index.js
Comment (dkotter) [inline assets/onboarding/steps/index.js:1]: Do we need this file? Says it's empty

File: includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php [hunk 22]
```diff
@@ -0,0 +1,157 @@
+<?php
+/**
+ * Class WC_REST_Square_Settings_Controller
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php [hunk 23]
```diff
@@ -0,0 +1,157 @@
...
+use WP_REST_Server;
+use WP_REST_Request;
+use WP_REST_Response;
+
+defined( 'ABSPATH' ) || exit;
+
+/**
+ * REST controller for saving Square's test/live account keys.
+ *
+ * This includes Live Publishable Key, Live Secret Key, Webhook Secret.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php [hunk 24]
```diff
@@ -0,0 +1,127 @@
+<?php
+/**
+ * Class WC_REST_Square_Settings_Controller
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php [hunk 25]
```diff
@@ -0,0 +1,127 @@
...
+use WP_REST_Server;
+use WP_REST_Request;
+use WP_REST_Response;
+
+defined( 'ABSPATH' ) || exit;
+
+/**
+ * REST controller for saving Square's test/live account keys.
+ *
+ * This includes Live Publishable Key, Live Secret Key, Webhook Secret.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php [hunk 26]
```diff
@@ -0,0 +1,189 @@
+<?php
+/**
+ * Class WC_REST_Square_Settings_Controller
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php [hunk 27]
```diff
@@ -0,0 +1,189 @@
...
+use WP_REST_Server;
+use WP_REST_Request;
+use WP_REST_Response;
+
+defined( 'ABSPATH' ) || exit;
+
+/**
+ * REST controller for saving Square's test/live account keys.
+ *
+ * This includes Live Publishable Key, Live Secret Key, Webhook Secret.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php [hunk 28]
```diff
@@ -0,0 +1,189 @@
...
+
+	/**
+	 * Allowed parameters.
+	 *
+	 * @var array
+	 */
+	private $allowed_params;
+
+	/**
+	 * WC_REST_Square_Settings_Controller constructor.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php [hunk 29]
```diff
@@ -0,0 +1,189 @@
...
+						'type'              => 'array',
+						'sanitize_callback' => '',
+					),
+				),
+			)
+		);
+	}
+
+	/**
+	 * Retrieve flag status.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Credit_Card_Payment_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php [hunk 30]
```diff
@@ -0,0 +1,157 @@
...
+
+	/**
+	 * Allowed parameters.
+	 *
+	 * @var array
+	 */
+	private $allowed_params;
+
+	/**
+	 * WC_REST_Square_Settings_Controller constructor.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php [hunk 31]
```diff
@@ -0,0 +1,157 @@
...
+						'type'              => 'string',
+						'sanitize_callback' => '',
+					),
+				),
+			)
+		);
+	}
+
+	/**
+	 * Retrieve flag status.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Cash_App_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php [hunk 32]
```diff
@@ -0,0 +1,127 @@
...
+
+	/**
+	 * Allowed parameters.
+	 *
+	 * @var array
+	 */
+	private $allowed_params;
+
+	/**
+	 * WC_REST_Square_Settings_Controller constructor.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php [hunk 33]
```diff
@@ -0,0 +1,127 @@
...
+						'type'              => 'string',
+						'sanitize_callback' => '',
+					),
+				),
+			)
+		);
+	}
+
+	/**
+	 * Retrieve flag status.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php]: Needs updating

File: includes/Admin/Rest/WC_REST_Square_Settings_Controller.php [hunk 34]
```diff
@@ -0,0 +1,218 @@
...
+						'type'              => 'string',
+						'sanitize_callback' => '',
+					),
+				),
+			)
+		);
+	}
+
+	/**
+	 * Retrieve flag status.
```
Comment (dkotter) [inline includes/Admin/Rest/WC_REST_Square_Settings_Controller.php]: Needs updating

File: includes/Framework/PaymentGateway/Payment_Gateway.php [hunk 35]
```diff
@@ -341,6 +338,12 @@ public function __construct( $id, $plugin, $args ) {
 		// default icon filter  @see WC_Payment_Gateway::$icon
 		$this->icon = apply_filters( 'wc_' . $this->get_id() . '_icon', '' );
 
+		$square_settings = get_option( 'wc_square_settings', array() );
+
+		$this->debug_mode = isset( $square_settings['debug_mode'] ) ? $square_settings['debug_mode'] : 'off';
+
+		$this->enable_customer_decline_messages = isset( $square_settings['enable_customer_decline_messages'] ) ? $square_settings['enable_customer_decline_messages'] : 'no';
```
Comment (dkotter) [inline includes/Framework/PaymentGateway/Payment_Gateway.php]: I think both of these can be simplified using the `??` operator

File: includes/Framework/PaymentGateway/Payment_Gateway_Plugin.php [hunk 36]
```diff
@@ -648,7 +647,11 @@ protected function add_debug_setting_notices() {
 
 		foreach ( $this->get_gateways() as $gateway ) {
 
-			if ( $gateway->is_enabled() && $gateway->is_production_environment() && ! $gateway->debug_off() ) {
+			// Get the debug mode.
+			$square_settings = get_option( 'wc_square_settings', array() );
+			$debug_mode      = isset( $square_settings['debug_mode'] ) ? $square_settings['debug_mode'] : 'off';
```
Comment (dkotter) [inline includes/Framework/PaymentGateway/Payment_Gateway_Plugin.php]:
```suggestion
			$debug_mode      = $square_settings['debug_mode'] ?? 'off';
```

File: includes/Handlers/Products.php [hunk 37]
```diff
@@ -75,6 +78,10 @@ public function __construct( Square\Plugin $plugin ) {
 			'missing_variation_sku' => __( "Please add an SKU to every variation of %s for syncing with Square. Each SKU must be unique and match the corresponding item's SKU in your Square account.", 'woocommerce-square' ),
 		);
 
+		// Get gift card features status.
+		$gift_card_settings      = get_option( 'woocommerce_gift_cards_pay_settings', array() );
+		$this->gift_card_enabled = isset( $gift_card_settings['enabled'] ) ? $gift_card_settings['enabled'] : 'no';
```
Comment (dkotter) [inline includes/Handlers/Products.php]:
```suggestion
		$this->gift_card_enabled =$gift_card_settings['enabled'] ?? 'no';
```

File: includes/Lifecycle.php [hunk 38]
```diff
@@ -293,6 +294,45 @@ protected function upgrade_to_3_0_2() {
 		delete_transient( 'wc_square_locations' );
 	}
 
+	/**
+	 * Upgrades to version 2.3.0.
```
Comment (dkotter) [inline includes/Lifecycle.php]:
```suggestion
	 * Upgrades to version 4.7.0.
```

File: includes/Lifecycle.php [hunk 39]
```diff
@@ -293,6 +294,45 @@ protected function upgrade_to_3_0_2() {
...
+				'enable_customer_decline_messages' => 'enable_customer_decline_messages',
+			),
+			false
+		);
+
+		// Mark upgrade complete.
+		update_option( 'wc_square_updated_to_4_7_0', true );
+
+		// Skip redirect existing users to the setup wizard on upgrade.
+		add_option( 'wc_square_show_wizard_on_activation', true );
```
Comment (dkotter) [inline includes/Lifecycle.php]: Should we ensure these options aren't autoloaded?

File: includes/Settings.php [hunk 40]
```diff
@@ -126,6 +139,124 @@ function( $fields ) {
...
+		);
+	}
+
+	/**
+	 * Show a notice to visit the wizard on plugin activation.
+	 *
+	 * @since 4.7.0
+	 */
+	public function show_visit_wizard_notice() {
+		if ( ! get_option( 'wc_square_onboarding_wizard_visited' ) ) {
```
Comment (dkotter) [inline includes/Settings.php]: Instead of having this larger block of code nested, we could invert this condition:
```suggestion
		if ( get_option( 'wc_square_onboarding_wizard_visited' ) ) {
			return;
		}
```

File: includes/Settings.php [hunk 41]
```diff
@@ -829,8 +983,14 @@ public function get_location_id() {
 	 */
 	public function get_locations() {
 
+		$is_ajax = wp_doing_ajax();
```
Comment (dkotter) [inline includes/Settings.php]: Now that this method is called by ajax, do we need any nonce verification here?

File: woocommerce-square.php [hunk 42]
```diff
@@ -29,7 +29,7 @@
 defined( 'ABSPATH' ) || exit;
 
 if ( ! defined( 'WC_SQUARE_PLUGIN_VERSION' ) ) {
-	define( 'WC_SQUARE_PLUGIN_VERSION', '4.6.0' ); // WRCS: DEFINED_VERSION.
+	define( 'WC_SQUARE_PLUGIN_VERSION', '4.7.0' ); // WRCS: DEFINED_VERSION.
```
Comment (dkotter) [inline woocommerce-square.php]:
```suggestion
	define( 'WC_SQUARE_PLUGIN_VERSION', '4.6.1' ); // WRCS: DEFINED_VERSION.
```

**Review by dkotter — CHANGES_REQUESTED** [review]
Let me know if there's any questions on the items I've flagged.

One other question I have is that this PR is set to merge into the `nux-react` branch. Curious on what this branch is and if it's still needed, or if this should be changed to `trunk`? cc / @Sidsector9 @faisal-alvi

File: assets/new-user-experience/onboarding/steps/business-location/index.js (hunk 17 above)
Comment (faisal-alvi) [reply assets/new-user-experience/onboarding/steps/business-location/index.js]: Yes, it is not specified where in the Figma though. I added https://squareup.com/dashboard/locations

File: assets/new-user-experience/onboarding/steps/business-location/index.js (hunk 18 above)
Comment (faisal-alvi) [reply assets/new-user-experience/onboarding/steps/business-location/index.js:168]: I haved added spaces so it is now:

`{ ( locationCount === 0 && noLocation ) ||`

But the following seems okay (without spaces), please let me know if this should also be changed.

`{intro}` and `options={[`

File: assets/new-user-experience/modules/configure-sync/index.js (hunk 10 above)
Comment (faisal-alvi) [reply assets/new-user-experience/modules/configure-sync/index.js:47]: We do not have a filter for options but I can see a filter in PHP `wc_square_sync_interval` to filter the selected interval. We are not using that in this new react-based settings page. To do so we may need to create an endpoint to get the value from the PHP filter into the JS file.

**Comment by faisal-alvi** [comment]
@dkotter thanks for the feedback. I've implemented the requested changes/suggestions and added some inline comments too. Please let me know if any changes are required. Note: All the spaces in the JS files are converted into tabs.

> this PR is set to merge into the nux-react branch. Curious on what this branch is and if it's still needed, or if this should be changed to trunk?

Yes, I changed the base to `trunk`.

> Do we need this file? Says it's empty

I can see the files are not empty. I'm not sure how this is empty at your end.

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
> I can see the files are not empty. I'm not sure how this is empty at your end.

Not seeing this anymore, wondering if this was due to the base branch being `nux-react` instead of `trunk` but in either case, good now

**Comment by qasumitbagthariya** [comment]
Hello @faisal-alvi 

Thanks for the PR.

In my initial testing, I found some CSS issues on the Chrome browser. Can you please check on your end?

**Screen resolution 1920*1080** 
image

**Screen resolution 1440*900**
image

**Screen resolution 1920*1080** 
image

I also noticed there are two scroll bars on the screen.
image

**Note:**
⚠️  My testing is still in progress.

**Comment by qasumitbagthariya** [comment]
Hello @faisal-alvi 

I've created a bug sheet where I'll add all the bugs, to avoid back and forth so that we can track all the bugs and their status. 

**Bug sheet:**
https://docs.google.com/spreadsheets/d/1OpDrRRWhpUmxokCGPYQasPjUyQ9HJGkxqVOc3oUqL7w/edit#gid=0

Note:
⚠️ My testing is still in progress.

Thanks.

**Comment by qasumitbagthariya** [comment]
@faisal-alvi @Sidsector9  ⚠️

When setting up a wizard (fresh setup) in the "Select your business location" section, it appears to be selecting a location, but it actually selects a Square application. After completing all the onboarding setups, when attempting to set up again(from the plugin page), it shows the business location. This inconsistency poses an issue. It's possible that we need to add one more screen, like selecting an application from Square, to address this.

Let me know if you need any help from my side to reproduce this flow.


https://github.com/woocommerce/woocommerce-square/assets/67687255/c49661ef-da5a-4f82-ad36-92a7b6d2c6c2


https://github.com/woocommerce/woocommerce-square/assets/67687255/ddacfc7a-09e8-4d07-96ca-e1f28dee40cb

**Comment by Sidsector9** [comment]
@qasumitbagthariya as discussed on Slack, this is good to go 👍

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------
 I have verified [NUX] Onboarding + Setting page in the `wizard_page` branch and functioning as intended, all the [issues](https://docs.google.com/spreadsheets/d/1OpDrRRWhpUmxokCGPYQasPjUyQ9HJGkxqVOc3oUqL7w/edit#gid=0) are resolved.

I tested the following on this branch:
- Onboarding + Setting page ✅ 
- Plugin > Square > Setup wizard ✅ 
- Compare all screens with figma ✅ 
- Gift card should not display if cc is off ✅  
- migration (Detailed Decline Messages and debug mode, Giftcard) ✅ 
- Cashapp ✅ 
- Credit payment ✅ 
- Import products ✅ 
- sync products ✅ 


https://github.com/woocommerce/woocommerce-square/assets/67687255/5f8cb06d-b00e-443c-ba25-b5fa0dc0a22d


https://github.com/woocommerce/woocommerce-square/assets/67687255/1cda83c8-1447-4c85-8ec2-e7424172fd75





**Testing Environment** 

<Details>

- WordPress: 6.5.3
- Theme: Storefront 4.5.5
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 8.9.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>

Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by vikrampm1** [comment]
@mattallan noting that this PR is awaiting your review.

**Review by mattallan — COMMENTED** [review]
Kudos @Sidsector9 for working on this change! Nice changes/improvements coming in this one which is cool to see!

I've tested this and noticed a couple of things:

### Square Onboarding on local dev site

When I pulled the latest branch on my local dev site, I clicked on Square onboarding, logged into my Square account and then after being redirected to my local store, I was basically stuck on this page:

image

A few issues I notice:
1. The HTML link is being printed
2. The button was taking me to `squareup.com/dashboard` instead of `squareup.com/dashboard/locations`
3. My Square account already has locations available

> My Square account already has locations available

Regarding this point ^ Does this problem only exist when testing on a local server? When I created a live site, going through the onboarding wizard worked perfectly fine 🤔 

### Debug notice linking to wrong page

This notice sends the merchant to the **WooCommerce > Settings > Payments > Square** page but there's no debug mode setting there anymore:

image

This setting was moved to **WooCommerce > Settings > Square**.

Something I noticed is there are now two settings related to debugging (Debug mode and enable logging): 
image

Previously these two settings had different functionalities:
1. Debug mode was specific to showing payment gateway related errors
2. Enable logging was specific to logging import and syncing errors

Is this distinction still the case? If so, I wonder if we should clarify this now that they're both on the same settings page?

### Existing store after updating

On my existing store that is already connected to Square and has orders/subscriptions purchased with Square, when I updated to this new version, I'm noticed the Square Onboarding menu item is loading:

image

Clicking on it sent me directly to a "Successfully connected" page without me having to do anything but I'm wondering if this should be automatic? Is it intended that all existing merchants see this onboarding wizard? Could we set the flag on upgrade.

### Viewing Square settings on local dev site

I'm not sure what's going on here but whenever I view a Square settings page on my local dev site I'm getting a gap at the top of the page. Here's a quick recording:

https://github.com/woocommerce/woocommerce-square/assets/2275145/1c9d4797-3438-4bed-b91f-6827edcb1785

I'm not seeing this on my live site and I don't have any PHP errors in logs or JS errors so I'm really not sure what would be causing this but I just wanted to raise it in case anyone else has seen it before.

**Comment by Sidsector9** [comment]
Thanks for reviewing @mattallan 

> Regarding this point ^ Does this problem only exist when testing on a local server? When I created a live site, going through the onboarding wizard worked perfectly fine 🤔

It should work locally, with and w/o https. Can you share the details of your stack you use for local development? It'll help us debug it further.

**Comment by mattallan** [comment]
Hey @Sidsector9, I've just been trying to reproduce it again locally but not having any luck 😢
It only happened straight after I updated Square and it's been a while since I've used Square locally so I'm wondering if I had some old invalid/expired Square keys still saved, and so after going through the wizard and being redirected back to the site it couldn't fetch any locations?

I've just been trying to reproduce similar issues to what I saw using that theory but still no luck, so I'm not sure. Sorry about the false report!

> Can you share the details of your stack you use for local development?

Yeah, it's a standard [Laravel Valet](https://laravel.com/docs/11.x/valet) local site, PHP 8.2, WC 8.8.3. Here's the SSR if that's easier:

<details>
`
### WordPress Environment ###

WordPress address (URL): http://woo.localhost
Site address (URL): http://woo.localhost
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.4
PHP Version: 8.2.16
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.6.0
(SecureTransport) OpenSSL/3.2.1

SUHOSIN Installed: –
MySQL Version: 5.7.44
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: wp_
Total Database Size: 48.77MB
Database Data Size: 32.49MB
Database Index Size: 16.28MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.33MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.92MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 2.41MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.52MB + Index: 4.20MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.56MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_newsletter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 5.02MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 2.05MB + Index: 1.16MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.22MB + Index: 0.19MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 12.52MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field-group: 1
attachment: 42
aw_workflow: 4
customize_changeset: 6
dummy_subscription: 5
global_product_addon: 1
page: 18
post: 11
product: 39
product_variation: 34
revision: 38
shop_coupon: 3
shop_order: 20
shop_subscription: 11
tribe_events: 1
tribe_venue: 1
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Square: by WooCommerce – 4.6.1
WooCommerce: by Automattic – 8.8.3

### Inactive Plugins (58) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
AutomateWoo: by WooCommerce – 5.5.5 (update to version 6.0.23 is available)
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.6 (update to version 3.1.5 is available)
Custom Functions Plugin: by Shamim – 1.1
Custom Start Date For WooCommerce Subscriptions: by Launch & Sell – 1.3.12
eCommerce Configuration By WP Engine: by WP Engine – 0.2.11
Gutenberg: by Gutenberg Team – 18.3.0
Jetpack: by Automattic – 13.4.2
Jetpack Boost: by Automattic - Jetpack Site Speed team – 3.3.0
Query Monitor: by John Blackbourn – 3.15.0
Relative URL: by Tunghsiao Liu – 0.1.8
Sensei Pro (WooCommerce Paid Courses): by Automattic – 4.0.2.2.6.4 (update to version 4.24.0.1.24.0 is available)
Smush: by WPMU DEV – 3.14.1
The Events Calendar: by The Events Calendar – 5.16.2.1
THSA Apps | One-click Switcher: by The Health Sciences Academy – 2.0.7
Variations as Single Product for WooCommerce: by StorePlugin – 1.0.0
WCPay Subscription Generator: by James Allan –
Woo All Products For Subscriptions: by Woo – 5.0.3 (update to version 5.0.4 is available)
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Affirm Gateway: by WooCommerce – 2.2.0 (update to version 2.3.0 is available)
WooCommerce Amazon Pay: by WooCommerce – 2.5.1
WooCommerce Blocks: by Automattic – 7.5.0
WooCommerce Bookings: by WooCommerce – 1.15.48 (update to version 2.1.2 is available)
WooCommerce Currency Converter: by WooCommerce – 1.6.25 (update to version 2.2.3 is available)
WooCommerce Deposits: by WooCommerce – 2.2.5 (update to version 2.2.8 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.26 (update to version 3.2.7 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.9.0 (update to version 2.9.3 is available)
WooCommerce Eway Payment Gateway: by WooCommerce – 3.4.1 (update to version 3.7.2 is available)
WooCommerce GoCardless Gateway: by WooCommerce – 2.5.9 (update to version 2.6.4 is available)
WooCommerce Memberships: by SkyVerge – 1.22.9 (update to version 1.26.5 is available)
WooCommerce Payfast Gateway: by WooCommerce – 1.6.5
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 2.7.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.43 (update to version 1.8.2 is available)
WooCommerce Pre-Orders: by WooCommerce – 2.1.0
WooCommerce Product Add-ons: by WooCommerce – 6.4.7 (update to version 6.8.3 is available)
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.4.3 (update to version 1.4.7 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.6.31 (update to version 2.4.8 is available)
WooCommerce SnapScan Gateway: by WooCommerce – 1.2.7
WooCommerce Square Helper: by WooCommerce – 1.0.5
WooCommerce Stripe Gateway: by WooCommerce – 8.2.0
WooCommerce Subscription Downloads: by WooCommerce – 1.4.1
WooCommerce Subscriptions: by WooCommerce – 6.3.1
WooCommerce Subscriptions - Custom Price String: by WooCommerce – 1.0.6
WooCommerce Subscriptions Core: by Automattic – 7.1.1
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.7.0
WooPayments: by Automattic – 7.6.0
Woo Product Bundles: by Woo – 7.0.1 (update to version 7.1.1 is available)
Woo Subscriptions Gifting - Recipient Address Update Fix: by Matt Allan –
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.5
WP Console: by Edi Amin – 2.4.1
WP Crontrol: by John Blackbourn – 1.16.2
WPForms Lite: by WPForms – 1.8.3.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Mail SMTP: by WP Mail SMTP – 3.8.0
WP phpMyAdmin: by Puvox.software – 5.2.1.02

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
new-variable (new-variable)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 78 MB

### WC Pages ###

Shop base: #1789 - /shop/
Cart: #7 - /cart/
Checkout: #941 - /checkout-block/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4 (update to version 4.6.0 is available)
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2023-08-23 03:27:13 +00:00
Options: ✔
Notes: 84
Onboarding: skipped

### Action Scheduler ###

Complete: 355
Oldest: 2024-04-09 00:10:13 +0000
Newest: 2024-06-02 00:58:14 +0000

Pending: 112
Oldest: 2024-05-08 01:27:53 +0000
Newest: 2026-05-20 03:02:57 +0000

Failed: 60
Oldest: 2024-02-09 05:36:16 +0000
Newest: 2024-06-02 00:58:11 +0000

Canceled: 910
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000


### Status report information ###

Generated at: 2024-05-21 08:37:00 +00:00
`
</details>

**Comment by faisal-alvi** [comment]
Hey @mattallan thanks for the report.

> Is this distinction still the case? If so, I wonder if we should clarify this now that they're both on the same settings page?

Yes, it is still the case. We can add a description to the settings field saying that enabling this setting will also enable debugging for other gateways/payment methods. How does that sound? However, I believe that seeing these fields on the generic settings page itself makes it obvious that they will be used globally for all payment gateways/methods.

> Clicking on it sent me directly to a "Successfully connected" page without me having to do anything but I'm wondering if this should be automatic?

After WP v6.5, on plugin activation, the auto-redirect is not supported anymore.

> Is it intended that all existing merchants see this onboarding wizard? Could we set the flag on upgrade.

Yes, we display the notice about the new onboarding wizard on upgrade to the existing users. It disappears when a user visits the onboarding wizard.

https://github.com/woocommerce/woocommerce-square/blob/367f4c3765557e14a1cb1cb610a2d86c9e6a2e93/includes/Settings.php#L216

> I'm getting a gap at the top of the page

I checked and it does not appear to me. Can you please confirm if there is any PHP warning behind that white strip?

**Comment by mattallan** [comment]
Thanks @faisal-alvi for the response!

> We can add a description to the settings field saying that enabling this setting will also enable debugging for other gateways/payment methods. How does that sound? However, I believe that seeing these fields on the generic settings page itself makes it obvious that they will be used globally for all payment gateways/methods.

Hmm, this comment makes me think I might be misunderstanding how these two settings work now 😅 

image

From my understanding, these two settings are independent of each other and have different functionalities:

1. Debug Mode: Toggles logging Square payment gateway errors on/off
2. Enable Logging: Toggles logging Square connection, import & sync errors on/off

Given this, merchants can have "Enable Logging" turned off and have Debug mode set to "Save to log" and errors from the checkout will still be logged. For me, this isn't clear from looking at these two settings which is why I was thinking that adding a description will help avoid merchant confusion

My understanding of these two settings might be incorrect now though so I'm happy for you to confirm and decide on whether a description is needed.

> Yes, we display the notice about the new onboarding wizard on upgrade to the existing users.

I wasn't referring to the notice, I was referring to the new **Square Onboarding** menu item found under the WooCommerce side menu 🙂 I understand this menu item also disappears when existing merchant visits the new setup wizard, however, say that I'm a merchant that has been using Square for many months/years, why would I click a "Square Onboarding" menu if they've already been connected and using Square?

My initial reaction when I saw this menu item was that clicking it was going to re-onboard me and so I can imagine merchants also being hesitant to click it themselves or being confused about what it's doing if they're an existing user of Square already.

I was thinking we should set `wc_square_onboarding_wizard_visited` to `1` by default for existing merchants unless there's a reason we want existing merchants to visit this new setup wizard?

This isn't a blocking issue and just my opinion so happy to move it to a separate issue to discuss it further or wait for feedback from merchants :)

> I checked and it does not appear to me. Can you please confirm if there is any PHP warning behind that white strip?

I cannot see any PHP warnings or notices behind the white strip.

From my latest testing, I can only reproduce it when the Square payment method is enabled, and Digital Wallets is enabled. So I'm guessing the problem is with trying to register my local domain with ApplePay on every page load of Square settings and it's erroring, maybe? I can't see anything in the logs that would suggest that though 🤔 

I just noticed I can reproduce the error on `trunk` so I think we move this off to a separate issue to investigate further or ignore it since it's most likely a local dev issue only :)

**Comment by faisal-alvi** [comment]
> My understanding of these two settings might be incorrect now though so I'm happy for you to confirm and decide on whether a description is needed.

We have internally decided to merge these settings together rather than keeping them separate as they seem to do more or less the same thing and we'll do that in a separate PR.

> I was thinking we should set wc_square_onboarding_wizard_visited to 1 by default for existing merchants unless there's a reason we want existing merchants to visit this new setup wizard?

Thanks for the suggestion. I was thinking of showing the new onboarding at least once even to the existing users as all users (new/existing) can visit the onboarding from the plugin list page as we have added the wizard link right beside the deactivate button. However, I have implemented your suggestion and set `wc_square_onboarding_wizard_visited` to 1 by default for existing merchants.

> I just noticed I can reproduce the error on trunk so I think we move this off to a separate issue

👍🏻 makes sense. Can you please create an issue ticket with the details?

**Comment by vikrampm1** [comment]
@mattallan can you review the updates from Faisal above and see if we can proceed moving this PR to the next step?

**Review by mattallan — APPROVED** [review]
> we'll do that in a separate PR.

Sounds good! Thanks @faisal-alvi 

> I have implemented your suggestion and set wc_square_onboarding_wizard_visited to 1 by default for existing merchants.

Thanks for making this change as well. I think this will avoid a lot of confusion to new merchants so I'm happy to see this one :) I have tested:

- [x] upgrading to this PR as an existing merchant and confirm the onboarding is not shown
- [x] new merchants still see the onboarding wizard

> Can you please create an issue ticket with the details?

Yea, I'll do some more investigating tomorrow and open an issue.

---

I've gone through the onboarding wizard again on a fresh site and confirmed it's looking good. 
Happy to approve this. Thanks @Sidsector9 and @faisal-alvi for all the work on this one

**Comment by jeffpaul** [comment]
> > My understanding of these two settings might be incorrect now though so I'm happy for you to confirm and decide on whether a description is needed.

> We have internally decided to merge these settings together rather than keeping them separate as they seem to do more or less the same thing and we'll do that in a separate PR.

@faisal-alvi @vikrampm1 please ensure that issue is created and linked to the source conversation here so we can track that, thanks!

**Comment by vikrampm1** [comment]
@jeffpaul yes it's already created and linked/referenced with this PR: https://github.com/woocommerce/woocommerce-square/issues/130

**Comment by dkotter** [comment]
@Sidsector9 @faisal-alvi There's quite a few merge conflicts here. Can you help get those cleaned up so this can move on to the next step?

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.5.4
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 9.0.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Git Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀
