### PR TITLE
fix/165: check if dependencies are loaded before showing onboarding process

### LINKED ISSUE #165: If cURL is not installed on the server, WooCommerce Square gives a fatal, instead of failing gracefully.
### To reproduce
1. Install the Square plugin on a server without cURL and go through the onboarding. 
2. Upon completion of onboarding, receive fatal error below. 

`Fatal error: Uncaught Error: Undefined constant "Unirest\CURLAUTH_BASIC" in /var/www/html/wp-content/plugins/woocommerce-square/vendor/apimatic/unirest-php/src/Configuration.php:54 Stack trace: #0 /var/www/html/wp-content/plugins/woocommerce-square/vendor/square/square/src/SquareClient.php(162): Unirest\Configuration::init(Object(Square\SquareClient)) #1 /var/www/html/wp-content/plugins/woocommerce-square/includes/API.php(71): Square\SquareClient->__construct(Array) #2 /var/www/html/wp-content/plugins/woocommerce-square/includes/Plugin.php(689): WooCommerce\Square\API->__construct('EAAAljYyrWz7dhj...', false) #3 /var/www/html/wp-content/plugins/woocommerce-square/includes/Settings.php(791): WooCommerce\Square\Plugin->get_api('EAAAljYyrWz7dhj...', false) #4 /var/www/html/wp-content/plugins/woocommerce-square/includes/Gateway.php(1051): WooCommerce\Square\Settings->get_locations() #5 /var/www/html/wp-includes/class-wp-hook.php(324): WooCommerce\Square\Gateway->filter_available_gateways(Array) #6 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array) #7 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(333): apply_filters('woocommerce_ava...', Array) #8 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Payments.php(89): WC_Payment_Gateways->get_available_payment_gateways() #9 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Payments.php(67): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments::has_gateways() #10 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php(106): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments->is_complete() #11 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php(305): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments->can_view() #12 [internal function]: Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->Automattic\WooCommerce\Admin\Features\OnboardingTasks\{closure}(Object(Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments)) #13 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php(306): array_filter(Array, Object(Closure)) #14 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php(240): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->get_viewable_tasks() #15 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php(412): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->is_complete() #16 /var/www/html/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php(434): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::setup_tasks_remaining() #17 /var/www/html/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::menu_task_count('') #18 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #19 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #20 /var/www/html/wp-admin/includes/menu.php(161): do_action('admin_menu', '') #21 /var/www/html/wp-admin/menu.php(422): require_once('/var/www/html/w...') #22 /var/www/html/wp-admin/admin.php(158): require('/var/www/html/w...') #23 /var/www/html/wp-admin/index.php(10): require_once('/var/www/html/w...') #24 {main} thrown in /var/www/html/wp-content/plugins/woocommerce-square/vendor/apimatic/unirest-php/src/Configuration.php on line 54`

### Expected behavior

If cURL is not installed, failing with a banner notice letting them know or similar would be preferred. If this plugin is installed on a server without cURL, it will bring the site down after completing onboarding. 

**Environment (please complete the following information):**
 - WordPress Version: 6.5.3
 - WooCommerce Version 9.0.1
 - WooCommerce Square Plugin Version - 4.7.0
 - Browser [e.g. chrome, safari] and Version - Firefox, Chromium, Safari
 
### Additional details

This happened on Studio, but we assume this will be replicable on any host without cURL.

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes #165 

This PR does the following if the dependencies are unmet:

1. Does not display the onboarding wizard.
2. Prevents direct access to the onboarding wizard via URL.
3. Disables the "Connect to Square" button on the Settings page.
4. Does not show the "Setup Wizard" link on the plugins page.

### Changelog entry

> Fix - Check if dependencies are loaded before showing onboarding process.

### CODE REVIEW

File: includes/Framework/Plugin.php [hunk 1]
```diff
@@ -363,7 +363,7 @@ public function plugin_action_links( $actions ) {
 		$custom_actions = array();
 
 		// settings url(s)
-		if ( $this->get_square_onboarding_link() ) {
+		if ( $this->get_square_onboarding_link() && 0 === count( wc_square()->get_dependency_handler()->get_missing_php_extensions() ) ) {
```
Comment (dkotter) [inline includes/Framework/Plugin.php]: Since we're doing this same thing a few times (getting a count of missing dependencies) wonder if we should add a new method that returns this count? Something like `$this->get_plugin()->get_dependency_handler()->get_number_of_missing_php_extensions()` and can then check if that equals zero or is greater than zero, as needed

Comment (Sidsector9) [reply includes/Framework/Plugin.php]: Added a check to test both missing PHP dependencies and functions:

```php
public function meets_php_dependencies() {
    return empty( $this->get_missing_php_extensions() ) && empty( $this->get_missing_php_functions() );
}
```

**Review by dkotter — COMMENTED** [review]
Tested and seems to work great, though we do still get a couple admin notices that mention connecting to Square and another one that provides a link to the onboarding:

Admin notices

Not critical but would be great to remove these if possible

**Review by dkotter — COMMENTED** [review]
Sorry for all the back and forth, this works great but in testing one last thing, you can still set up a sandbox connection. Once that's done, it causes the same fatal error to occur. If we can easily prevent that connection as well, that would be great

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

-------------

 I have checked this issue in the fix/165 branch and the related issue is resolved and working as expected.

**Testing Environment** 

<Details>

- WordPress: 6.5.5
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.1
- WooCommerce - 9.1.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


**Before Fix**

image

**After Fix**

image
image
image
image

Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by vikrampm1** [comment]
@james-allan this PR is ready for your review.

**Review by diegocurbelo — APPROVED** [review]
Changes look good, and tests well.. including the notices fix:

Screenshot 2024-07-19 at 6 02 10 PM

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 10.7.0, node version 20.15.1)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>


Next Step- Ready to Merge 🚀
